//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeSharing.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BikeSharing.Web.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon....
        /// </summary>
        public static string Cities_Barcelona {
            get {
                return ResourceManager.GetString("Cities_Barcelona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon....
        /// </summary>
        public static string Cities_Boston {
            get {
                return ResourceManager.GetString("Cities_Boston", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon....
        /// </summary>
        public static string Cities_MexicoCity {
            get {
                return ResourceManager.GetString("Cities_MexicoCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York City.
        /// </summary>
        public static string Cities_NewYork {
            get {
                return ResourceManager.GetString("Cities_NewYork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon....
        /// </summary>
        public static string Cities_SanFrancisco {
            get {
                return ResourceManager.GetString("Cities_SanFrancisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seattle.
        /// </summary>
        public static string Cities_Seattle {
            get {
                return ResourceManager.GetString("Cities_Seattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find thousands of bikes in New York City and Seattle. Our smart bikes provide the perfect combination of comfort and intelligence..
        /// </summary>
        public static string Cities_Text {
            get {
                return ResourceManager.GetString("Cities_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridget Gaila Beckett, 38.
        /// </summary>
        public static string Clients_Author {
            get {
                return ResourceManager.GetString("Clients_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seattle.
        /// </summary>
        public static string Clients_City {
            get {
                return ResourceManager.GetString("Clients_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I save a lot of time from my morning commute while enjoying a daily workout on my way to work. I love to use my mobile app to track my routes and share with friends..
        /// </summary>
        public static string Clients_Quote {
            get {
                return ResourceManager.GetString("Clients_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Footer_Contact {
            get {
                return ResourceManager.GetString("Footer_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a sample demo application for developers built with educational purposes only. Source code is available at: .
        /// </summary>
        public static string Footer_Info {
            get {
                return ResourceManager.GetString("Footer_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Footer_Privacy {
            get {
                return ResourceManager.GetString("Footer_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Footer_Terms {
            get {
                return ResourceManager.GetString("Footer_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BikeSharing360 is a smart bike sharing system with 10,000 bikes distributed in 650 stations located throughout New York City and Seattle..
        /// </summary>
        public static string Hero_Text {
            get {
                return ResourceManager.GetString("Hero_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and book bikes and get personalized recommendations of events in your city. Get your bike, purchase tickets to events, and ride to them..
        /// </summary>
        public static string HiW_Book_Text {
            get {
                return ResourceManager.GetString("HiW_Book_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string HiW_Book_Title {
            get {
                return ResourceManager.GetString("HiW_Book_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover a fun and efficient new way to move around your city. Learn about new routes and get personalized recommendations on routes. Riding a bike and buyinh what you need on the road was never so easy and enjoyable..
        /// </summary>
        public static string HiW_Discover_Text {
            get {
                return ResourceManager.GetString("HiW_Discover_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string HiW_Discover_Title {
            get {
                return ResourceManager.GetString("HiW_Discover_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave your car in your garage and get fit while you enjoy and discover your city. Let BikeSharing360 suggest custom rides just for you and go where you need while you enjoy what you like..
        /// </summary>
        public static string HiW_Enjoy_Text {
            get {
                return ResourceManager.GetString("HiW_Enjoy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy.
        /// </summary>
        public static string HiW_Enjoy_Title {
            get {
                return ResourceManager.GetString("HiW_Enjoy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it Works.
        /// </summary>
        public static string HiW_Title {
            get {
                return ResourceManager.GetString("HiW_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download App.
        /// </summary>
        public static string Intelligent_Download {
            get {
                return ResourceManager.GetString("Intelligent_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map layer.
        /// </summary>
        public static string Intelligent_Map {
            get {
                return ResourceManager.GetString("Intelligent_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On your mark, get set, get ready for lots of fun! Download our app, go green, and discover an easy way to find and rent bikes. Our bikes and mobile app allows you have a unique and personal riding experience. Get event recommendations and purchase what you need where you are while you enjoy your ride..
        /// </summary>
        public static string Intelligent_Text {
            get {
                return ResourceManager.GetString("Intelligent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent App.
        /// </summary>
        public static string Intelligent_Title {
            get {
                return ResourceManager.GetString("Intelligent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Menu_Cities {
            get {
                return ResourceManager.GetString("Menu_Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our clients.
        /// </summary>
        public static string Menu_Clients {
            get {
                return ResourceManager.GetString("Menu_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it Works.
        /// </summary>
        public static string Menu_HiW {
            get {
                return ResourceManager.GetString("Menu_HiW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent App.
        /// </summary>
        public static string Menu_Intelligent {
            get {
                return ResourceManager.GetString("Menu_Intelligent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Menu_SignIn {
            get {
                return ResourceManager.GetString("Menu_SignIn", resourceCulture);
            }
        }
    }
}
